on: pull_request
name: PR

jobs:
  gitHubActionForNpm:
    name: Validating
    runs-on: ubuntu-latest

    steps:
      - name: Checking out default branch
        uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '10.x'
      - name: Running yarn install, prettier and type checks
        run: |
          yarn install --check-files --cache-folder .ycache
          yarn prettier-check
          yarn type-check
      - name: Run Unit tests
        run: yarn test-unit

  gitHubActionForNpmWin:
    name: Validating
    runs-on: windows-latest

    steps:
      - name: Checking out default branch
        uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '10.x'
      - name: Running yarn install, prettier and type checks
        run: |
          yarn install --check-files --cache-folder .ycache
          yarn prettier-check
          yarn type-check
      - name: Run Unit tests
        run: yarn test-unit
